---

- hosts: localhost
  become: True
  connection: local
  tasks:

  - name: Auto Sudo
    copy:
      content: "{{ username }} ALL=NOPASSWD:ALL"
      dest: "/etc/sudoers.d/{{ username }}"

  - name: The docker repo key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
  
  - name: The docker repo list
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch edge"
      filename: "docker.list"

  - name: The kube repo key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  
  - name: The kube repo list
    apt_repository:
      repo: "deb [arch=amd64] http://apt.kubernetes.io/ kubernetes-xenial main"
      filename: "kube.list"

  - name: Install Packages
    apt:
      state: latest
      update_cache: yes
      name:
        - apt-transport-https
        - ca-certificates
        - chromium-browser
        - curl
        - dnsutils
        - docker-ce
        - git
        - git-core
        - docker-compose
        - kubectl
        - net-tools
        - pass
        - pwgen
        - rng-tools
        - software-properties-common
        - tree
        - virtualbox
        - vagrant
        - vim
        - whois
